const favouritePlatformsDataDelete = {
  sys: { type: 'Array' },
  total: 1,
  skip: 0,
  limit: 100,
  items: [{
    update: () => 'update',
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'rq9f9siz5b6e' } },
      id: '13QaZGsSHgyAggqI22MQsW',
      type: 'Entry',
      createdAt: '2018-12-05T10:32:38.993Z',
      updatedAt: '2018-12-05T19:34:40.188Z',
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedCounter: 7,
      version: 26,
      publishedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedVersion: 25,
      firstPublishedAt: '2018-12-05T10:32:39.389Z',
      publishedAt: '2018-12-05T19:34:40.188Z',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'favouritePlatform' } },
    },
    fields: {
      userId: { 'en-US': '9999' },
      platform: {
        'en-US': [{
          sys: {
            type: 'Link',
            linkType: 'Entry',
            id: '6ymHMrgkH6q6WGggqQ2aMs',
          },
        }, { sys: { type: 'Link', linkType: 'Entry', id: '5ZDQx5dW6cqweY26GqK8s6' } }],
      },
    },
  }],
};

const favouritePlatformsDataAdd = {
  sys: { type: 'Array' },
  total: 1,
  skip: 0,
  limit: 100,
  items: [{
    update: () => 'update',
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'rq9f9siz5b6e' } },
      id: '13QaZGsSHgyAggqI22MQsW',
      type: 'Entry',
      createdAt: '2018-12-05T10:32:38.993Z',
      updatedAt: '2018-12-05T19:34:40.188Z',
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedCounter: 7,
      version: 26,
      publishedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedVersion: 25,
      firstPublishedAt: '2018-12-05T10:32:39.389Z',
      publishedAt: '2018-12-05T19:34:40.188Z',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'favouritePlatform' } },
    },
    fields: {
      userId: { 'en-US': '9999' },
      platform: {
        'en-US': [{
          sys: {
            type: 'Link',
            linkType: 'Entry',
            id: '6ymHMrgkH6q6WGggqQ2aMs',
          },
        }],
      },
    },
  }],
};

const platformsData = {
  sys: { type: 'Array' },
  total: 4,
  skip: 0,
  limit: 100,
  items: [{
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'rq9f9siz5b6e' } },
      id: 'kd2AXxjFu0KYI8QSQCO8Y',
      type: 'Entry',
      createdAt: '2018-12-04T20:29:52.991Z',
      updatedAt: '2018-12-04T20:29:59.924Z',
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedCounter: 1,
      version: 2,
      publishedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedVersion: 1,
      firstPublishedAt: '2018-12-04T20:29:59.924Z',
      publishedAt: '2018-12-04T20:29:59.924Z',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'platform' } },
    },
    fields: { title: { 'en-US': 'test' }, imageName: { 'en-US': 'test' } },
  }, {
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'rq9f9siz5b6e' } },
      id: '5ZDQx5dW6cqweY26GqK8s6',
      type: 'Entry',
      createdAt: '2018-12-03T20:32:00.700Z',
      updatedAt: '2018-12-03T20:43:42.453Z',
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedCounter: 2,
      version: 13,
      publishedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedVersion: 12,
      firstPublishedAt: '2018-12-03T20:32:08.859Z',
      publishedAt: '2018-12-03T20:43:42.453Z',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'platform' } },
    },
    fields: { title: { 'en-US': 'Angular 2+' }, imageName: { 'en-US': 'angular' } },
  }, {
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'rq9f9siz5b6e' } },
      id: '662lRdvU6AKOG6AkQKY2eU',
      type: 'Entry',
      createdAt: '2018-12-03T20:43:49.993Z',
      updatedAt: '2018-12-03T20:43:56.743Z',
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedCounter: 1,
      version: 10,
      publishedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedVersion: 9,
      firstPublishedAt: '2018-12-03T20:43:56.743Z',
      publishedAt: '2018-12-03T20:43:56.743Z',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'platform' } },
    },
    fields: { title: { 'en-US': 'AngularJs' }, imageName: { 'en-US': 'angular' } },
  }, {
    sys: {
      space: { sys: { type: 'Link', linkType: 'Space', id: 'rq9f9siz5b6e' } },
      id: '6ymHMrgkH6q6WGggqQ2aMs',
      type: 'Entry',
      createdAt: '2018-12-03T14:04:43.587Z',
      updatedAt: '2018-12-03T14:04:51.713Z',
      environment: { sys: { id: 'master', type: 'Link', linkType: 'Environment' } },
      createdBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      updatedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedCounter: 1,
      version: 7,
      publishedBy: { sys: { type: 'Link', linkType: 'User', id: '7ykSMqxCfJyoulNng6Gro5' } },
      publishedVersion: 6,
      firstPublishedAt: '2018-12-03T14:04:51.713Z',
      publishedAt: '2018-12-03T14:04:51.713Z',
      contentType: { sys: { type: 'Link', linkType: 'ContentType', id: 'platform' } },
    },
    fields: { title: { 'en-US': 'Android' }, imageName: { 'en-US': 'android' } },
  }],
};

module.exports = {
  favouritePlatformsDataDelete,
  platformsData,
  favouritePlatformsDataAdd,
};
